# Generated by Django 3.0.7 on 2020-06-16 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='level',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='species',
        ),
    ]
