# Generated by Django 3.0.7 on 2020-06-16 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_api', '0005_auto_20200616_0548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(default=models.IntegerField(default=0, verbose_name='base attack')),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(default=models.IntegerField(default=0, verbose_name='base defense')),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='hp',
            field=models.IntegerField(default=models.IntegerField(default=0, verbose_name='base hp')),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='s_attack',
            field=models.IntegerField(default=models.IntegerField(default=0, verbose_name='base special attack'), verbose_name='full attack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='s_defense',
            field=models.IntegerField(default=models.IntegerField(default=0, verbose_name='base special defense'), verbose_name='special defense'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='speed',
            field=models.IntegerField(default=models.IntegerField(default=0, verbose_name='base speed')),
        ),
    ]
