# Generated by Django 3.0.7 on 2020-06-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_api', '0007_auto_20200618_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_attack',
            field=models.IntegerField(default=0, verbose_name='base attack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_defense',
            field=models.IntegerField(default=0, verbose_name='base defense'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_hp',
            field=models.IntegerField(default=0, verbose_name='base hp'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_s_attack',
            field=models.IntegerField(default=0, verbose_name='base special attack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_s_defense',
            field=models.IntegerField(default=0, verbose_name='base special defense'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_speed',
            field=models.IntegerField(default=0, verbose_name='base speed'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='s_attack',
            field=models.IntegerField(default=0, verbose_name='special attack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='s_defense',
            field=models.IntegerField(default=0, verbose_name='special defense'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
