# Generated by Django 3.0.7 on 2020-06-18 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_api', '0010_auto_20200618_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='speed',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
