# Generated by Django 3.0.7 on 2020-06-18 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_api', '0011_auto_20200618_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='level',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
