# Generated by Django 3.0.7 on 2020-06-18 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_api', '0013_auto_20200618_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_attack',
            field=models.IntegerField(default=0, verbose_name='base attack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_defense',
            field=models.IntegerField(default=0, verbose_name='base defense'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_hp',
            field=models.IntegerField(default=0, verbose_name='base hp'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_s_attack',
            field=models.IntegerField(default=0, verbose_name='base special attack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_s_defense',
            field=models.IntegerField(default=0, verbose_name='base special defense'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_speed',
            field=models.IntegerField(default=0, verbose_name='base speed'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='iv',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='next_exp',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='number',
            field=models.CharField(default=3, max_length=30),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='s_attack',
            field=models.IntegerField(default=0, verbose_name='special attack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='s_defense',
            field=models.IntegerField(default=0, verbose_name='special defense'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='speed',
            field=models.IntegerField(default=0),
        ),
    ]
