# Generated by Django 3.0.7 on 2020-06-19 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_api', '0014_auto_20200618_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='b_hp',
            field=models.IntegerField(default=0, editable=False, verbose_name='base hp'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='name',
            field=models.CharField(default='default name', max_length=30),
        ),
    ]
