# Generated by Django 3.0.7 on 2020-06-19 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_api', '0015_auto_20200618_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='attack',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_attack',
            field=models.IntegerField(default=0, editable=False, verbose_name='base attack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_defense',
            field=models.IntegerField(default=0, editable=False, verbose_name='base defense'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_s_attack',
            field=models.IntegerField(default=0, editable=False, verbose_name='base special attack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_s_defense',
            field=models.IntegerField(default=0, editable=False, verbose_name='base special defense'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='b_speed',
            field=models.IntegerField(default=0, editable=False, verbose_name='base speed'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='defense',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='exp',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', editable=False, max_length=1),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='hp',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='iv',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='level',
            field=models.IntegerField(default=1, editable=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='next_exp',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='s_attack',
            field=models.IntegerField(default=0, editable=False, verbose_name='special attack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='s_defense',
            field=models.IntegerField(default=0, editable=False, verbose_name='special defense'),
        ),
    ]
