# Generated by Django 3.0.7 on 2020-06-19 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_api', '0016_auto_20200618_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='speed',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
