# Generated by Django 3.0.7 on 2020-06-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_api', '0017_auto_20200618_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='prev_exp',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
