# Generated by Django 3.0.7 on 2020-06-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_api', '0018_pokemon_prev_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='evolve_chain',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='sprite',
            field=models.ImageField(default='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.pn', editable=False, upload_to=None),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='number',
            field=models.CharField(default=3, editable=False, max_length=30),
        ),
    ]
