# Generated by Django 3.0.7 on 2020-06-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_api', '0019_auto_20200619_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='sprite',
            field=models.URLField(default='https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/3.png', editable=False),
        ),
    ]
