# Generated by Django 3.0.7 on 2020-06-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_api', '0020_auto_20200619_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='main_pic',
            field=models.URLField(default='https://assets.pokemon.com/assets/cms2/img/pokedex/full/3.png', editable=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='number',
            field=models.CharField(default=3, max_length=30),
        ),
    ]
