# Generated by Django 3.0.6 on 2020-05-29 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Exhibit',
        ),
    ]
