# Generated by Django 3.0.6 on 2020-05-29 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20200529_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exhibit',
            name='project_link',
        ),
    ]
