# Generated by Django 3.0.6 on 2020-06-01 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_auto_20200529_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='picture',
            field=models.ImageField(default='project_default.jpg', upload_to='project_pics'),
        ),
    ]
