# Generated by Django 3.0.6 on 2020-06-02 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_forumpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForumPost',
        ),
    ]
